org.name=devnautica
app.fullname=d3v-utils-bash-scripts
app.name=d3v-utils
app.language=bash
app.type=lib
version.previous.buildnumber=17
version.previous.tag=0.0.17
version.current.buildnumber=18
version.current.tag=0.0.18
