org.name=devnautica
app.fullname=d3v-utils-bash-scripts
app.name=d3v-utils
app.language=bash
app.type=lib
version.previous.buildnumber=14
version.previous.tag=0.0.14
version.current.buildnumber=15
version.current.tag=0.0.15
