org.name=$d3v{ORG_NAME}
app.fullname=$d3v{PROJECT_FULL_NAME}
app.name=$d3v{PROJECT_NAME}
app.language=$d3v{PROJECT_LANGUAGE}
app.type=$d3v{PROJECT_APP_TYPE}
version.previous.buildnumber=0
version.previous.tag=0.0.0
version.current.buildnumber=1
version.current.tag=0.0.1
